[package]
name = "zen-markdown"
version = "0.1.1"
edition = "2024"
description = "A fast, native, zen-like markdown editor built with Rust + egui"
license = "MIT"
repository = "https://github.com/thingnoy/zen-markdown"
readme = "README.md"

[dependencies]
eframe = { version = "0.29", default-features = false, features = ["default_fonts", "glow", "persistence"] }
egui = "0.29"
egui_extras = { version = "0.29", features = ["syntect"] }
pulldown-cmark = "0.12"
rfd = "0.15"
serde = { version = "1", features = ["derive"] }

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
strip = true
